title: "Dr. O. Rama Devi"
description: "Professor | Artificial Intelligence & Data Science | Researcher | Author"
theme: minimal

url: "https://YOUR-GITHUB-USERNAME.github.io"
baseurl: ""   # keep empty if this is a user site: YOUR-GITHUB-USERNAME.github.io

markdown: kramdown
kramdown:
  input: GFM

author:
  name: "Dr. O. Rama Devi"
  email: "odugu.rama@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
