title: "Dr. O. Rama Devi"
description: "Professor | Artificial Intelligence & Data Science | Researcher | Author"
theme: minima

# Because this is a user site: https://oduguramadevi.github.io
url: "https://oduguramadevi.github.io"
baseurl: ""   # must be empty for user site

author:
  name: "Dr. O. Rama Devi"
  email: "odugu.rama@gmail.com"

# Show these pages in the top navigation bar
header_pages:
  - publications.md
  - books.md
  - patents.md
  - activities.md
  - awards.md
